spring.application.name=rateLimit
# Add h2 db config

#Use H2 File Database (Un-comment below line for File DB)
#spring.datasource.url=jdbc:h2:mem:banking-db
spring.datasource.url=jdbc:h2:file:./data/banking-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# h2 console path
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# include message in error response
server.error.include-message=always